log:
  enabled: true
  level: debug

backendStore:
  databaseMigration: true
  databaseConnectionCheck: true

postgresql:
  enabled: true

  primary:
    persistence:
      enabled: false

artifactRoot:
  s3:
    enabled: true

minio:
  enabled: true

  persistence:
    enabled: false
